// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pllnboggbgghjyunmwdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbG5ib2dnYmdnaGp5dW5td2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNTM2NDIsImV4cCI6MjA3NTkyOTY0Mn0.LPP6YT9q1qyBKiTcggYlkCgj6-E6d8Fq8mmsdcCbCY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});